# bookstack/docker-compose.yml

services:
  # 1. Servicio de la Aplicación Django
  app:
    build: .
    container_name: bookstack_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/src
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=tu_secret_key_para_desarrollo
      - DEBUG=True
      - POSTGRES_DB=bookstack_db
      - POSTGRES_USER=bookstack_user
      - POSTGRES_PASSWORD=bookstack_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CACHE_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/2
    depends_on:
      - db
      - redis

  # 2. Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: bookstack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookstack_db
      - POSTGRES_USER=bookstack_user
      - POSTGRES_PASSWORD=bookstack_pass

  # --- Servicio de Caché Redis ---
  redis:
    image: redis:7-alpine
    container_name: bookstack_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- Servicio del Trabajador Celery ---
  worker:
    build: .
    container_name: bookstack_worker
    volumes:
      - .:/app
    working_dir: /app/src
    command: celery -A config worker -l info
    environment:
      - SECRET_KEY=tu_secret_key_para_desarrollo
      - DEBUG=True
      - POSTGRES_DB=bookstack_db
      - POSTGRES_USER=bookstack_user
      - POSTGRES_PASSWORD=bookstack_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CACHE_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/2
    depends_on:
      - db
      - redis

# Define los volúmenes nombrados
volumes:
  postgres_data:
  redis_data:
